# Generated by Django 3.0.2 on 2020-03-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200306_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Set book as returned', '可以还书'),)},
        ),
    ]
